title:   Kha Pham
logo: "/images/aKha.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  Results-driven data engineer, product owner and business system analyst with experiences and a track record of delivering innovative technical solutions that enhance the experience of both customers and analytic professionals. Proficient in SQL, Python with a validated competence to automate dashboards, streamline processes, and provide tactical direction to stakeholders using easy-to-understand language. Skilled in analyzing behavioral data, identifying business gaps, and developing solutions that meet the needs of both internal and external stakeholders.
  <br><br><br>
  <a href="https://www.linkedin.com/in/kha-pham-22228077/">View My LinkedIn Profile</a>
  <br><br><br>
  <a href="https://www.notion.so/Portfolio-Kha-Pham-ded620c3d522461d8937fe1de75f907e">View My Portfolio on Notion Samples</a>
  
theme: jekyll-theme-minimal   
 
